sudo: false
language: python
notifications:
  email: false
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
  - pypy
  - nightly
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install flake8==2.6.2; fi
  - pip install -r tests/requirements.txt
  - npm install -g phantomjs-prebuilt
script:
  - make test
after_success:
  codecov
